### ISSUE TITLE
Scrape Something New candidates

### ISSUE THREAD

**Issue by Floppy** [DemocracyClub/UK-Political-Parties#3]
@mhl we had this conversation on the mailing list, but I thought I'd drop it here as well. For your scrapers, we're now publishing Something New candidates as machine-readable data if you want to use it. See https://somethingnewuk.github.io/candidates/datapackage.json for a jumping-off point.

**Comment by symroe** [comment]
Closing this as it now belongs here:

https://github.com/mysociety/yournextmp-popit/issues
