### ISSUE TITLE
feature request: auto-crop party emblems to the non-white region

### ISSUE THREAD

**Issue by mhl** [DemocracyClub/UK-Political-Parties#7]
It turns out that there are some party emblems that, strangely, are huge, but with the emblem only in the extreme top left of the image, e.g.:
- https://yournextmp.popit.mysociety.org/organizations/party:83/image/54ce632895590a10203203f8

It would be great if these were cropped to be the minimum size that only excludes all white pixels before being imported to Open Electoral Commission.

**Comment by symroe** [comment]
Fixed in 7754097585dbff20d679de08a2a3d67f3f544b74.  Let me know if you see any more problems!
